config/routes.rb
Metube::Application.routes.draw do
  get '/videos/gladiator' => 'videos#show_gladiator', as: 'gladiator_video'
end

Metube::Application.routes.draw do
  get '/videos/air_force_one' => 'videos#show_air_force_one', as: 'air_force_one_video'
end

Metube::Application.routes.draw do
  get '/videos/game_of_thrones' => 'videos#show_game_of_thrones', as: 'game_of_thrones_video'
end

Metube::Application.routes.draw do
  get '/videos/modern_family' => 'videos#show_modern_family', as: 'modern_family_video'
end

Metube::Application.routes.draw do
  get '/posts/san_francisco' => 'posts#show_san_francisco'
end

Metube::Application.routes.draw do
  get '/posts/austin' => 'posts#show_austin'
end

Metube::Application.routes.draw do
 root 'videos#show_all'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show_san_francisco
  end

  def show_austin
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show_gladiator
    @video = {
      :title => "Gladiator",
      :description => "This is when Russell Crowe shows he is the man",
      :youtube_id => "FI1ylg4GKv8"
    }
  end

  def show_air_force_one
  end

  def show_game_of_thrones
  end

  def show_modern_family
  end

  def show_all
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Metube</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/show_austin.html.erb
<h1>Austin</h1>
<img src = "http://www.codero.com/blog/wp-content/uploads/2012/11/Austin-skyline.jpg">

app/views/posts/show_san_francisco.html.erb
<h1> San Francisco </h1>

<img src = "http://geektreks.com/wp-content/uploads/2013/02/11.jpg">

app/views/videos/show_air_force_one.html.erb
<h1>Air Force One</h1>

<iframe width="420" height="315" src="//www.youtube.com/embed/sOUoNy7EmPA" frameborder="0" allowfullscreen></iframe>

<p>What's up.</p>

app/views/videos/show_all.html.erb
<ul> Great video clips from movies and TV
  <li><%= link_to "Gladiator", gladiator_video_path %></li>
  <li><%= link_to "Air Force One", air_force_one_video_path %></li>
  <li><%= link_to "Game of Thrones", game_of_thrones_video_path %></li>
  <li><%= link_to "Modern Family", modern_family_video_path %></li>
</ul>

app/views/videos/show_game_of_thrones.html.erb
<h1>Eddard!</h1>

<iframe width="560" height="315" src="//www.youtube.com/embed/KpZnb0q24mk" frameborder="0" allowfullscreen></iframe>

<p>Shows everyone what's up.</p>

app/views/videos/show_gladiator.html.erb
<h1><%= @video[:title] %></h1>

<iframe width="420" height="315" src="//www.youtube.com/embed/<%= @video[:youtube_id] %>" frameborder="0" allowfullscreen></iframe>

<p><%= @video[:description] %></p>

app/views/videos/show_modern_family.html.erb
<iframe width="420" height="315" src="//www.youtube.com/embed/O5uuMr1YEyE" frameborder="0" allowfullscreen></iframe>